### ISSUE TITLE
keybinding idea

### ISSUE THREAD

**Issue by lukesmurray** [greenmeen/zotero-roam#1]
Hey awesome project. I noticed there are some issues with keybindings and I think the package [is-hotkey](https://www.npmjs.com/package/is-hotkey) could be helpful here. On mac the default binding don't work. When the user presses `alt + q` it comes out as `alt + œ`.

Here's a codepen which demonstrates how [isHotKey works](https://codepen.io/lukesmurray/pen/ExZXNmO?editors=1111). You can basically just write literate event handlers like `alt+q` or `mod+z` which work across systems (mod maps to cmd on mac and ctrl on windows). It might even make setting the user settings easier since users can specify hotkeys as `alt+q` instead of as an object of booleans.

I noticed there aren't any dependencies in the project. I think that's great `isHotKey` is a one file project and has an MIT license so you could take the source code as is and include it if you want. 

Anyway feel free to completely ignore this since it's your project and I didn't read all the shortcut handling code so this may not actually work but I thought it might be an easy fix.  Cheers!

**Comment by greenmeen** [comment]
Wow this looks like an awesome library!
The extension already has two dependencies (autoComplete + Tribute), so I'm hesitant to add any more. I also don't want to break with the current structure to define shortcuts because all users would have to update their code & I'd rather not ask them to do that, lots of folks don't have a grasp of JavaScript. If Roam changes its plugin system in the future though (aka, no longer requires end users to tinker with code directly) I will definitely seriously consider using is-hotkey to handle shortcuts. Thanks so much for the suggestion!
