### ISSUE TITLE
Notes are not synchronized to Roam

### ISSUE THREAD

**Issue by IamMarek** [greenmeen/zotero-roam#16]
Using the latest version, I've noticed that the notes for my items are not synchronized to zotero. After a brief investigation, I've found out that the api `<userOrGroupPrefix>/items` does not return any notes. The notes can be retrieved using the `<userOrGroupPrefix>/items/<itemKey>/children` api method. 

Is there a plan to include the call of  `<userOrGroupPrefix>/items/<itemKey>/children` api in the getItemMetadata method?

**Comment by greenmeen** [comment]
Hi there! To clarify the `<userOrGroupPrefix>/items` call does include note elements, but the API key needs to have permission to access user notes - otherwise the extension won't be able to retrieve them.
`<userOrGroupPrefix>/items` includes both top-level items (i.e, papers, works, etc.) and attachments (PDFs, linked files, notes, etc.). If that's what you use in your `dataURI` setting you will get your notes as well provided your API key allows the extension to do so. It's the `<userOrGroupPrefix>/items/top` that is restrictive to top-level items.

**Comment by greenmeen** [comment]
Will close this for now - if you've done the above and are still running into issues, comment here & add some screenshots of your Zotero + Roam displays to help troubleshoot!
