### ISSUE TITLE
Update Imported Metadata (Quality of Life Feature Request)

### ISSUE THREAD

**Issue by cameroncruz** [greenmeen/zotero-roam#3]
Hi! Loving this extension, it's been a lifesaver for creating my ideal Zotero->Roam workflow. Thank you!

One inconvenience I've been running into is updating the notes for a particular source. For example, I may have already imported a source's metadata, which at the time contained no notes. Later, I extract PDF annotations as notes into Zotero, and would like to import those notes into Roam.

Currently, the extension will simply prepend all the metadata into the source's existing page in Roam, duplicating the metadata I already imported.

Ideally, the existing metadata in the Roam page would simply be updated to reflect updates in Zotero.

How difficult might this be to implement?

**Comment by greenmeen** [comment]
Pretty difficult, actually :)
After the metadata got added to the page, it's not really possible for the extension to be able to tell which blocks on that page contain the metadata. Because anyone could have subsequently added blocks at the top, bottom, middle, or deleted/rearranged blocks.
If everyone stored the metadata under a parent block (say "Metadata::"), then it'd be possible to just update its child blocks -- but it's not the case. 

I've had a request for an option to import notes separately, and will be implementing it soon. Would that solve your issue?

**Comment by cameroncruz** [comment]
Ah that makes sense, thank you for the clarification. I think separate note import would certainly help!

**Comment by cameroncruz** [comment]
Also, being able to customize the notes parsing function beyond just split char would be super helpful - I keep getting some unwanted <h1> and <span> tags in the imported text

**Comment by greenmeen** [comment]
Yes the parser is still a work in progress, lots of potential HTML tags that could be present in there. I'll keep working on it :) let me know if there are other tags you've seen besides h1 and span!
