### ISSUE TITLE
How to update a imported page?

### ISSUE THREAD

**Issue by mgdreamingstar** [greenmeen/zotero-roam#6]
After adding some more notes to an article in Zotero, how to update the page of it in Roam without deleting it and re-import it?

**Comment by mgdreamingstar** [comment]
I use the 'Right' domain and ‘Archive' domain to put some keyword about the article.
When I change some thing, the import metadata button will import lots of duplicate infos, not only the updated ones.

**Comment by greenmeen** [comment]
With Roam's current structure, there is no way to "update" metadata that has been imported, as it is.
So reimporting it is indeed the only way sadly. This is because the extension can't detect or map content from Roam blocks to an item's metadata in Zotero - since each user has a different template.
