### ISSUE TITLE
Theme background conflict

### ISSUE THREAD

**Issue by paride92** [greenmeen/zotero-roam#7]
I recently started to use Roam Research desktop app, therefore I decided to not Stylus anymore in order to have a black theme for my Roam and instead to use a CSS dark theme. I noticed that I have some problem visualizing the menus or the text of the Zotero-roam. There is a way to harmonize them through some settings in the aspect of Zotero-Roam?
![Cattura](https://user-images.githubusercontent.com/38630681/122671907-1839b980-d1c9-11eb-9ba0-0f86d319822b.PNG)

**Comment by greenmeen** [comment]
What's the theme you're using?

The extension has a lot of built-in classes you can use to style elements. It has very little added CSS and mostly uses Blueprint's class system so that if you use custom themes changes are reflected without need for extra work. (Here I believe changing the background color of the card would be most of the adjustment needed : `.bp3-card {background-color: black;}` for example)

**Comment by paride92** [comment]
I am using this theme https://github.com/linuz90/better-roam-research

I don't have any programming knowledge, where should I put `.bp3-card {background-color: black;}`? I don't think that is in the roam.js page but I can't figure it out.

**Comment by greenmeen** [comment]
It's for **roam/css** ; you can add a code block on the `roam/css` page, select CSS as the language, then write `.bp3-card {background-color: black;}` inside.

I haven't tested that particular theme, so there might be other modifications needed.

**Comment by paride92** [comment]
It works perfectly. Thank you very much for the help and for your fantastic work.
